FROM python:3

ADD lastfmapi2.py /

RUN pip install requests
RUN pip install requests_cache
RUN pip install json
RUN pip install datetime
RUN pip install time
RUN pip install IPyhon.core.display
RUN pip install pandas
RUN pip install math
